### ISSUE TITLE
Comparing Allele-specific HiC matrices

### ISSUE THREAD

**Issue by StephenRicher** [dozmorovlab/HiCcompare#25] opened 2021-11-30 11:57 UTC
Hi,

Thanks for developing this fantastic tool. I was wondering if this tool was recommended for comparing between HiC matrices of different alleles (e.g. A1 vs. A2). 

Thanks,
Stephen

**Comment by mdozmorov** [comment] 2021-11-30 13:21
We have not tested it, but by design, HiCcompare should be ideal for allele-specific Hi-C matrix comparison. It will eliminate all technical biases and detect if there are interaction differences associated with allele-specific regions.

Hope that helps, closing, but please ask more and let know how it went.

**Closed as completed by mdozmorov** 2021-11-30 13:21 UTC
